### ISSUE TITLE
Getting TypeError when FinStat returns null for city

### ISSUE THREAD

**Issue by vstruhar** [hubipe/finstat#2]
First, thanks for the package, it sped up my implementation by far.

I found an issue when I searched for "Falcon", FinStat API is returning a company that has no city (it is set to null).
And that the reason why I get:
```
Argument 3 passed to Hubipe\FinStat\Response\Autocomplete\AutocompleteResult::__construct() must be of the type string, null given
```

I found that it was passed [here](https://github.com/hubipe/finstat/blob/master/src/Parser/Autocomplete/AutocompleteParser.php#L45)

**Comment by hubipe** [comment]
Hi @vstruhar,
thanks for the report. Fixed and released as version 1.0.9, you can update with composer.
